### PR TITLE
Fix warnings for inheritance

### PR DESCRIPTION
**Pull request by mli-ableton**
@gck-ableton @mak-ableton: Please review! Thanks!

### CODE REVIEW

**Comment by gck-ableton** [comment]
I like this.  But we should talk about the versioning.

**Comment by mli-ableton** [comment]
Hey @mak-ableton, @gck-ableton: I will work on your comments now and will rebase locally because it's simpler. But I will reply to your comments before force pushing.

**Comment by mli-ableton** [comment]
@gck-ableton @mak-ableton: please take another look! Besides the work that resulted from your comments, there are two more new commits: https://github.com/Ableton/aqt-stylesheets/commit/d3200fe38a0ab5bcd9ddc3a96a09616b1e880fae and https://github.com/Ableton/aqt-stylesheets/commit/a757a57dff989ea4d9c0b51dd509913c06351d84.

**Comment by mak-ableton** [comment]
Very nice!

**Comment by mli-ableton** [comment]
@mak-ableton: LGTY?

**Comment by mak-ableton** [comment]
:+1:

**Pull request merged**
