### PR TITLE
Fix the IID of our QML plugins.

### PR DESCRIPTION
**Pull request by cah-ableton**
Make our IIDs match the "correct" QML style, as seems to be enforced in newer versions of QT.

### CODE REVIEW

**Review by gck-ableton — APPROVED** [review]
This looks right.  Either I mixed up to what to put in the IID back in the day or I was missing the documentation for it.  Anyway according to https://doc.qt.io/qt-5/qtplugin.html this is the way to go.

**Comment by cah-ableton** [comment]
Did I break the AppVeyor build?  The error _looks_ unrelated...

**Comment by gck-ableton** [comment]
> Did I break the AppVeyor build? The error _looks_ unrelated...

```
CMake Error at CMakeLists.txt:85 (find_package):
  By not providing "FindQt5Quick.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt5Quick",
  but CMake did not find one.
```
but only for VS2017...?

**Comment by cah-ableton** [comment]
@gck-ableton is this alright with you (Appveyor version bump of Qt to 5.11.3)?

**Review by ala-ableton — APPROVED** [review]
Since I authored https://github.com/Ableton/aqt-stylesheets/commit/fc1c652fbfae40c9ad92e45fd376b30883c34eef, using Qt 5.11.3 LGTM 👍

**Comment by cah-ableton** [comment]
Thanks both!

**Pull request merged**
