### PR TITLE
Disable MSVC warning C4242 produced by Qt5.6 headers

### PR DESCRIPTION
**Pull request by ala-ableton**
@gck-ableton, @mak-ableton, @mli-ableton : please review, thanks!

### CODE REVIEW

**Comment by mak-ableton** [comment]
LGTM, but CI doesn't like it for some reason...

**Comment by ala-ableton** [comment]
Google Test has moved and the repo on GoogleSource.com now only contains a README.md.

**Comment by gck-ableton** [comment]
Doesn't this need changing appveyor.yml, too, then?

**Comment by ala-ableton** [comment]
@gck-ableton: oops. Addressed in https://github.com/Ableton/aqt-stylesheets/pull/41/commits/0f414b50b986d8006ba7358998d864706add05ac. But why isn't AppVeyor running?

**Comment by ala-ableton** [comment]
Actually AppVeyor is running, but it's not posting commit statuses back to GitHub... I am investigating now.

**Comment by gck-ableton** [comment]
LGTM, once rebased.

**Pull request merged**
