### PR TITLE
Update cpp-peglib to beaa0346ca76e52e32a23fd04eb7605cb7313059

### PR DESCRIPTION
**Pull request by toh-ableton**
https://github.com/yhirose/cpp-peglib/blob/beaa0346ca/peglib.h

RFC @gck-ableton
FYI @csd-ableton

### CODE REVIEW

**Comment by toh-ableton** [comment]
In Gregor's absence, would you be able to review this, @ala-ableton?

**Comment by ala-ableton** [comment]
@toh-ableton could you please make the PR title, PR description and commit message agree?

**Comment by toh-ableton** [comment]
I've updated the description; and I'll update the commit message when I squash the commits.

**Comment by ala-ableton** [comment]
@toh-ableton thanks for updating the PR description. However, I really would like to see the final commit message, which should explain why we are updating `cpp-peglib` and why to that commit in particular.

**Comment by toh-ableton** [comment]
I'm a bit confused about what you want to me to do now. We're updating to this beaa0346ca because it's the lastest master, and we need it because we need it to build a PR on one of our private repos.

**Comment by toh-ableton** [comment]
@ala-ableton ptal

**Comment by ala-ableton** [comment]
LGTM :+1:

**Comment by gck-ableton** [comment]
👍 nachträglich.

**Pull request merged**
