### PR TITLE
Update cpp-peglib to make it build with more versions of clang

### PR DESCRIPTION
**Pull request by jab-ableton**
This is not the current master, but it removes the `enabler` variable
that led to an undefined reference with more versions of clang beyond
version 5.

https://github.com/yhirose/cpp-peglib/blob/559836cda1/peglib.h

### CODE REVIEW

**Comment by jab-ableton** [comment]
@gck-ableton Could you have a look?

**Comment by jab-ableton** [comment]
@gck-ableton How about now?

**Comment by gck-ableton** [comment]
> @gck-ableton How about now?

Looks good!  Can you merge on your own?

**Comment by ala-ableton** [comment]
@jab-ableton please rebase on top of the latest `master`. I also added you to the Ableton org so you can merge this PR (and don't even need to make a fork in the future).

**Pull request merged**
